Use Type=notify
minio/minio-service pull request #33
Opened 2023-05-02 16:36 UTC by WGH-

This tells systemd that `minio` supports startup notification protocol, and will wait until it tells it's ready before launching dependent (`After=`) services.

See https://github.com/minio/minio/pull/17062

Note that unlike unlike the linked PR, this change is not backward compatible: attempting to run `Type=notify` service with old MinIO binary will result in startup timing out. This should not be merged until new MinIO version is released (partly because some of the documentation advises to download the unit file directly from master), and possibly it might be a good idea to delay it a bit further than that.

2023-05-02 20:29 UTC, harshavardhana approved these changes

2023-05-02 20:29 UTC, harshavardhana requested changes

2023-05-02 20:29 UTC, harshavardhana commented on linux-systemd/minio.service
> +Type=notify
you need to make this change in the `distributed/minio.service` file as well

2023-05-03 04:08 UTC, harshavardhana approved these changes

2023-05-03 04:08 UTC, merged

2023-05-04 19:06 UTC, MichaIng commented
This currently breaks startup, the service start times out, i.e. MinIO does not sent the notification.

2023-05-04 19:12 UTC, WGH- commented
Yeah, this shouldn't have been merged before MinIO release after all.